src/main/java/elisa/rest/model/Message.java
package elisa.rest.model;

import java.sql.Timestamp;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import elisa.service.Utils;


@XmlAccessorType(XmlAccessType.FIELD) //Marshall only class fields into XML elements, ignore getters
@XmlRootElement(name = "message")
//@XmlType //Needed for the ContentViewResolver to detect object to be unmarshalled

//@XmlType(propOrder = { "field2", "field1",.. })
@XmlType( name = "message", 
    propOrder = {
        "author",
        "username",
        "subject",
        "date",
        "body",
        "messageType", 
        "systemAffected", 
        "id", 
        "logbook", 
        "encoding", 
        "hasAttachments",
        "hasReplies", 
        "replyTo",
        "threadHead", 
        "valid", 
        "status",
        "host_ip",
        "attachments",
        "optionalAttributes"
    })

/**
 * 
 * <p/>
 * Every field is mapped into a XML element with the same name.
 * XMLElement annotation is used to ovveride element name.
 *  
 * @author lucamag
 *
 */
@Component
public class Message {
	
	//this class should contain the displayed properties
	//should be configurable from the form menu
	private static final Log log = LogFactory.getLog(Message.class.getName());
	
	//Id of the message
    private long id;
    
    private static Utils utils = new Utils();
	
    //Thread ID of the top thread ID
    @XmlElement(name="thread_head")
    private long threadHead;
    
    //Logbook
    private  int logbook;
    
    //Kind of boolean, from metadata
    @XmlElement(name="has_replies")
    private  int hasReplies;
    
    //Message ID of the parent in the thread
    @XmlElement(name="reply_to")
    private  long replyTo;
    
    //Kind of boolean 
    @XmlElement(name="has_attachments")
    private  int hasAttachments;
    //Encoding
    private  int encoding;
    //Valid
    private  String valid;
  
    //Date coming from metadata
    
    @XmlElement(name="date")
    private Date date;
    
    //Text of the message from metadata
    private String body;
    
    // Non optional attributes
    @XmlElement(name="message_type")
    private String messageType;
    
    private String subject;
    private String author;
    //@XmlTransient
    private String status;
    @XmlElement(name="username")
    private String username;
    @XmlElement(name="host_ip")
    private String host_ip;

    //Sytem affected array. Made by multiple entries in attribute MID, SA_ATTR_NUMBER, VALUE1, etc.
    @XmlElement(name = "systems_affected")
    private SystemAffectedList systemAffected = new SystemAffectedList(); 
    //private List<String> systemAffected;
    
    //List of the all optional attributes (name=value, curly bracket separated)
    @XmlElement(name="options")
    private OptionList optionalAttributes;
    
    @XmlElement(name="attachments")
    private AttachmentList attachments ;
    
    
    public Message() {
        //logbook = 70;
        hasReplies = 0;
        replyTo = 0;
        hasAttachments = 0;
        encoding = 3;
        valid="valid";
        status="open";
        
    }
    
	
	public long getID() {
		return id;
	}

	public void setID(long id) {
		this.id = id;
	}
	
	public int getLogbook() {
        return logbook;
    }

    public void setLogbook(int i) {
        this.logbook=i;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Timestamp timestamp) {
        long milliseconds = timestamp.getTime() + (timestamp.getNanos() / 1000000);
        this.date = new Date(milliseconds);
    }


	public int getHasReplies() {
		return hasReplies;
	}

	public void setHasReplies(int hasReplies) {
		this.hasReplies = hasReplies;
	}

	public long getReplyTo() {
		return replyTo;
	}

	public void setReplyTo(long replyTo) {
		this.replyTo = replyTo;
	}

	public long getThreadHead() {
		return threadHead;
	}

	public void setThreadHead(long threadHead) {
		this.threadHead = threadHead;
	}

	public int getHasAttachments() {
		return hasAttachments;
	}

	public void setHasAttachments(int hasAttachments) {
		this.hasAttachments = hasAttachments;
	}

	public int getEncoding() {
	    return encoding;
	}
	
	public void setEncoding(int e) {
	    this.encoding=e;
	}

	public String getValid() {
        return valid;
    }
    public void setValid(String v) {
        this.valid=v;
    }

	public String getBody() {
		return  body;
	}
	public void setBody(String body) {
		this.body = body;
	}

	public String getMessageType() {
		return messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getHost_ip() {
		return host_ip;
	}

	public void setHost_ip(String host_ip) {
		this.host_ip = host_ip;
	}

	public SystemAffectedList getSystemAffected() {
		return systemAffected;
	}

	public void setSystemAffected(List<String> saArr) {
		this.systemAffected.setList(saArr);
	}
	
	public void setSystemAffectedFromString(String sa_string) {
	    //From database, the system affected string is a "|" separated list of system affected
	    List<String> sa = new LinkedList<String>();
	    //if(sa_string==null)
	        //log.error("WTF?????????");
	    String[] row_sa = sa_string==null?null:sa_string.replaceAll("\\[", "").replaceAll("\\]","").split("\\;");
	    if(row_sa==null)
	        sa.add(sa_string);
	    else 
	        for(String s:row_sa)
	            sa.add(s);
	    
	    this.systemAffected.setList(sa);
	}
	
	public String getSystemAffectedAsString() {
	    return StringUtils.join(this.systemAffected.getList(), ',');
    }
	

	public OptionList getOptionalAttributes() {
		return optionalAttributes;
	}

	public void setOptionalAttributes(List<Option> optattrlist) {
	    if(this.optionalAttributes==null)
	        this.optionalAttributes = new OptionList();
		this.optionalAttributes.setList(optattrlist);
	}

	
	public AttachmentList getAttachments() {
	    return this.attachments;
	}
	
	public void setAttachmentList(AttachmentList list) {
	    if (attachments==null)
	            this.attachments= new AttachmentList();
	    this.attachments = list;
	}
   
	public void addAttachment(Attachment a) {
	    this.attachments.getList().add(a);
	}
	
	public String getBodyHTML() {
	    return utils.markdown2html(body);
	}

	
}

src/main/java/elisa/rest/model/SystemAffectedList.java
package elisa.rest.model;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang.StringUtils;

@XmlRootElement(name="systems_affected")
@XmlType

public class SystemAffectedList {
	
	private int count;
	private List<String> sa;

	public SystemAffectedList() {}
	
	public SystemAffectedList(List<String> l) {
		this.sa = l;
		this.count = l.size();
	}

	public int getCount() {
		return count;
	}
	public void setCount(int count) {
		this.count = count;
	}
	
	@XmlElement(name="system_affected")
	public List<String> getList() {
		return sa;
	}
	public void setList(List<String> l) {
		this.sa = l;
		this.count = sa.size();
	}
	
	public String getListString() {
	    return StringUtils.join(this.sa,  " | ");
	}
	
	
}

src/main/webapp/WEB-INF/jsp/deniedpage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>
 
Access Denied!</h1><p>
 
Only admins can see this page!</p></body>
</html>

src/main/webapp/WEB-INF/jsp/include.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<%
String service_name="ELisA REST API";
%>

<%
String service_version="v3.0";
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<style type="text/css">

/*********************/
/***** General *******/
/*********************/ 

body {
  font-family: Verdana, Helvetica, Arial, sans-serif;
  margin:0px 30px 0px 30px; padding:0px;
  width:  95%
}

div {
  /*line-height: 1.5em;*/
}

a {
  color: #008800;
  text-decoration: none;
  font-weight: bold;
}

h1 {
  margin: 0px;
  margin-bottom: .2em;
}

h2 {
  font-family: Verdana, Helvetica, Arial, sans-serif;
  margin-top: 8px;
  margin-bottom: 8px;
  padding: 6px;
  border-top: 1px solid #dddddd;
  border-bottom: 1px solid #dddddd;
  border-left: 2px solid #999999;
  border-right: 2px solid #999999;
  color: #007700;
  /*background-color: #eeeeee;*/
  font-weight: normal;
  font-size: larger;
}


 #messages {
font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;
width:100%;
border-collapse:collapse;
}
#messages td, #messages th 
{
font-size:1em;
border:1px solid #98bf21;
padding:3px 7px 2px 7px;
}
#messages th 
{
font-size:1.1em;
text-align:left;
padding-top:5px;
padding-bottom:4px;
background-color:#A7C942;
color:#ffffff;
}
#messages tr.alt td 
{
color:#000000;
background-color:#EAF2D3;
}

.fix_width_column { width: 150px; }

/*
#directives tr.alt td 
{
color:#000000;
background-color:#EAF2D3;
}
*/
</style>

src/main/webapp/WEB-INF/jsp/loginpage.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
 
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API - LDAP Login page</title>
</head>
<body>
 
<h1>
 
Login</h1><div id="login-error">
 
${error}</div><form action="../../j_spring_security_check" method="post" >
 
 
 
<p>
 
 
 <label for="j_username">Username</label>
 <input id="j_username" name="j_username" type="text" />
</p><p>
 
 
 <label for="j_password">Password</label>
 <input id="j_password" name="j_password" type="password" />
</p><input  type="submit" value="Login"/>        
  
</form></body>
</html>

src/main/webapp/WEB-INF/jsp/rest_attachment.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] </h2> 
	<p>
	Attachment with ID ${attachment_id} created for message ID ${message_id}.

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_attachments.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] List of attachments for message : ${message_id} </h2>
	<table id="messages">
		<tr>
		<th class="fix_width_column"><b>Attachments</b></th>
		</tr>
		<c:forEach var="attachment" items="${attachments.list}">
			<tr>
				<td><a href="${attachment.link}"> ${attachment.fileName} </a></td>
			<tr>
		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<%@ page import="javax.servlet.http.HttpUtils.*"%>
<%
    String myURI = request.getRequestURI();
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>
		[
		<%=service_name%>
		<%=service_version%>
		] ${messages.count} messages - <a href="${messages.prev}">
			&lt;&lt; </a> - <a href="${messages.next}"> &gt;&gt; </a>
	</h2>
	<table id="messages">
		<c:forEach var="message" items="${messages.messages}">
			<th class="fix_width_column"><a href="messages/${message.ID}">
					${message.ID}</a></th>
			<th>${message.date} - <a href="?author=${message.author}">
					${message.author}</a> - ${message.subject}
			</th>
			<tr>
				<td class="fix_width_column">Body</td>
				<td>${message.bodyHTML}</td>
			</tr>
			<tr class="alt">
				<td class="fix_width_column">Message Type</td>
				<td><a href="?message_type=${message.messageType}">
						${message.messageType}</a></td>
			</tr>
			<tr>
				<td class="fix_width_column">Systems Affected</td>
				<td><c:forEach var="sa" items="${message.systemAffected.list}">
						<a href="?systems_affected=${sa}"> ${sa}</a> |
       				</c:forEach></td>
			</tr>
			<tr class="alt">
				<td class="fix_width_column">Attachments</td>
				<td><c:forEach var="att" items="${message.attachments.list}">
						<a href="${att.link}"> ${att.fileName}</a> |
       				</c:forEach></td>
			</tr>

		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_message.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] </h2>  

	<table id="messages">

		<tr>
			<th class="fix_width_column">ID: ${message.ID}</th>
			<th><b> ${message.date} - ${message.author} -
					${message.subject}</b></th>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Author</td>
			<td>${message.author}</td>
		</tr>
		<tr>
			<td class="fix_width_column">Username</td>
			<td>${message.username}</td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Date</td>
			<td>${message.date}</td>
		</tr>
		<tr>
			<td class="fix_width_column">Subject</td>
			<td>${message.subject}</td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Body</td>
			<td>${message.bodyHTML}</td>
		</tr>
		<tr>
			<td class="fix_width_column">Message Type</td>
			<td>${message.messageType}</td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">System Affected</td>
			<td>${message.systemAffected.listString}</td>
		</tr>
		<tr>
			<td class="fix_width_column">Options</td>
			<td><c:forEach var="option"
					items="${message.optionalAttributes.list}">
         ${option.name}: ${option.value} |
      		 </c:forEach></td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Attachments</td>
			<td><c:forEach var="att" items="${message.attachments.list}">
					<a href="${att.link}"> ${att.fileName}</a> |
       				</c:forEach></td>
		</tr>
		<tr>
			<td class="fix_width_column">Has Attachments</td>
			<td>${message.hasAttachments}</td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Has Replies</td>
			<td>${message.hasReplies}</td>
		</tr>
		<tr>
			<td class="fix_width_column">Reply to</td>
			<td>${message.replyTo}</td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Tread Head</td>
			<td>${message.threadHead}</td>
		</tr>
		<tr>
			<td class="fix_width_column">Valid</td>
			<td>${message.valid}</td>
		</tr>
		<tr class="alt">
			<td class="fix_width_column">Status</td>
			<td>${message.status}</td>
		</tr>



	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_message_text.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
<h2>[ <%=service_name%> <%=service_version%> ] Body for the message: ${message_id} </h2>
<table id="messages">
    <tr>
    <th>Body</th>
    </tr>
    <tr>
      <td>${message_body.text}</td>
    </tr>
</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_mt.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] Message types and metadata</h2>
	<table id="messages">
		<tr>
		<th><b>Message type name</b></th>
		<th><b>Options</b></th>
		<th><b>Preset System Affected</b></th>
		</tr>
		<c:forEach var="mt" items="${mt.list}">
			<tr>
				<td> ${mt} </td>
				<td><a href="./mt/${mt}/opt"> /opt </a></td>
				<td><a href="./mt/${mt}/sa"> /sa </a></td>
			<tr>
		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_opt.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] Details for message option: "${opt.name}" of message type "${mt}"</h2>
	<table id="messages">
		<tr>
			<th><b>Name</b></th>
			<th><b>Possible values</b></th>
			<th><b>Type</b></th>
			<th><b>Comment</b></th>
		</tr>

		<tr>
			<td><a href="."> ${opt.name} </a></td>
			<td>${opt.possibleValues}</td>
			<td>${opt.type}</td>
			<td>${opt.comment}</td>
			
			<c:forEach var="opt" items="${opt.childOptions.list}">
				<tr>
					<th><b>Inner Option Name</b></th>
					<th><b>Possible values</b></th>
					<th><b>Type</b></th>
					<th><b>Comment</b></th>
				</tr>

				<tr>
					<td>${opt.name}</td>
					<td>${opt.possibleValues}</td>
					<td>${opt.type}</td>
					<td>${opt.comment}</td>
				<tr>
			</c:forEach>
		<tr>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_opts.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] Message options for message type: "${mt}" </h2>
	<table id="messages">
		<tr>
		<th><b>Name</b></th>
		<th><b>Possible values</b></th>
		<th><b>Type</b></th>
		<th><b>Comment</b></th>
		<th><b># Inner Options</b></th>
		</tr>
		<c:forEach var="opt" items="${opt.list}">
			<tr>
				<td><a href="./opt/${opt.name}"> ${opt.name} </a></td>
				 <td>${opt.possibleValues}</td>
     			 <td>${opt.type}</td>
    			  <td>${opt.comment}</td>
    			  <td>${opt.childOptions.count}</td>
			<tr>
		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_sa.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2>[ <%=service_name%> <%=service_version%> ] List of possible system affected</h2>
	<table id="messages">
		<tr>
		<th><b>System Affected</b></th>
		</tr>
		<c:forEach var="sa" items="${sa.list}">
			<tr>
				<td> ${sa} </td>
			<tr>
		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/rest_samt.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ELisA REST API</title>
</head>
<body>
	<h2> [ <%=service_name%> <%=service_version%> ] List of preset systems affected per message type "${mt}"</h2>
	<table id="messages">
		<tr>
		<th><b>System Affected</b></th>
		</tr>
		<c:forEach var="sa" items="${sa.list}">
			<tr>
				<td> ${sa} </td>
			<tr>
		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/WEB-INF/jsp/welcome.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>EliSA REST interface</title>
</head>
<body>
<h2> [ <%=service_name%> <%=service_version%> ]  Welcome </h2>
<p> 
The <a href="https://atlasop.cern.ch/elisa/defaultList.htm?logbook=ATLAS">ELisA </a> API is a RESTful service, which means it uses HTTP
requests to interact with ATLAS logbook messages. Clients can use ELisA's REST API to create, reply, insert, update and search among logbook messages.

<p> You can use any language or tool that supports HTTP calls to access the ELisA REST API. </p>

<p> Project documentation: <a href="https://atlasdaq.cern.ch/elisa_api_alpha/server.html#documentation"> https://atlasdaq.cern.ch/elisa_api_alpha/server.html#documentation</a> 
<p> REST interface specification, with functions specification and data formats: <a href="https://atlasdaq.cern.ch/elisa_api_alpha/protocol.html" > https://atlasdaq.cern.ch/elisa_api_alpha/protocol.html </a>  
<p> Jira: <a href="https://its.cern.ch/jira/browse/ELISA"> https://its.cern.ch/jira/browse/ELISA </a>
<p>

Your browser is an HTTP client at the end... use the REST interface to
<ul>
<li> <a href="./messages"> browse logbook messages </a> </li>
<li> <a href="./mt"> browse message metadata </a> </li>
</ul>

</body>
</html>